# Generated by Django 4.0.2 on 2022-02-03 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='variety.jpg', upload_to='variety')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(max_length=100)),
                ('image', models.ImageField(default='meal.jpg', upload_to='meal')),
                ('spicy', models.CharField(choices=[('Not', 'Not'), ('Mild', 'Mild'), ('Medium', 'Medium'), ('Hot', 'Hot'), ('Extra Hot', 'Extra Hot')], max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('breakfast', models.BooleanField()),
                ('lunch', models.BooleanField()),
                ('dinner', models.BooleanField()),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.variety')),
            ],
        ),
    ]
