# Generated by Django 4.0.2 on 2022-02-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0004_alter_meal_options_alter_variety_options_meal_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='variety',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
