# Generated by Django 4.0.2 on 2022-02-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0005_alter_meal_slug_alter_variety_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='menu',
            field=models.TextField(),
        ),
    ]
