# Generated by Django 4.0.2 on 2022-02-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0006_alter_meal_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='discount',
            field=models.FloatField(default=8.0),
        ),
        migrations.AddField(
            model_name='meal',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
