# Generated by Django 4.0.2 on 2022-02-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0007_meal_discount_meal_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='discount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='display',
            field=models.BooleanField(),
        ),
    ]
