# Generated by Django 4.0.2 on 2022-02-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0014_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_icon.jpg', upload_to='profile'),
        ),
    ]
