# Generated by Django 4.0.2 on 2022-02-28 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcart',
            old_name='spicy',
            new_name='how_spicy',
        ),
    ]
