# Generated by Django 4.0.2 on 2022-03-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0008_alter_paidorder_payment_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidorder',
            name='cart_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paidorder',
            name='payment_code',
            field=models.CharField(max_length=50),
        ),
    ]
