# Generated by Django 4.0.2 on 2022-03-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0009_alter_paidorder_cart_no_alter_paidorder_payment_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
